### ISSUE TITLE
Exception when presenting request creation. 

### ISSUE THREAD

**Issue by markst** [zendesk/zendesk_sdk_ios#103]
Getting an exception when attempting to present request creation screen:

```objc
[ZDKRequests showRequestCreationWithNavController:self.navigationController];
```

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'NSConcreteAttributedString initWithString:: nil value'
```

![image](https://cloud.githubusercontent.com/assets/274318/10723205/90b9f104-7c0c-11e5-89c2-be1dbe5a2029.png)

**Comment by markst** [comment]
using `1.4.1.4` btw.

**Comment by hermanolsson** [comment]
@markst we're seeing the same issue. Are you replacing any (but not all) of the strings with a strings bundle?

https://developer.zendesk.com/embeddables/docs/ios/customization#customizing-strings-and-localization

I was about to post an issue about this, so I might as well add my thoughts here.

We see the crash above when using the strings bundle to replace some of the strings, and only in release builds. Also using 1.4.1.4.

**Comment by RonanMcH** [comment]
Hey @markst and @hermanolsson ,
I believe this error happening because the "ZendeskSDKStrings.bundle" may not be added properly to your project or targets within your project.  Could you make sure that the "ZendeskSDK.bundle" and the "ZendeskSDKStrings.bundle" are in the "Copy Bundle Resources" dropdown menu under the "Build Phases" tab (as shown in the screenshot attached) and if they are not, could you please add them? They must be there for every target that is using the Zendesk SDK. If you are using a custom Strings bundle, make sure you check that is there also?
<img width="1275" alt="buildphasessetup" src="https://cloud.githubusercontent.com/assets/12997923/10753624/48c3395e-7c8a-11e5-8998-45051f9d9249.png">

Hope this helps,
Ronan.

**Comment by markst** [comment]
thanks @RonanMcH adding `ZendeskSDKStrings.bundle` to bundle resolves.
Not sure if it's some setup with the podspec which is wrong?

You can make `NSAttributedString` less volatile by initializing it as follows:
```objc
[[NSAttributedString alloc] initWithString:string ?: @""]
```

**Comment by StevenDiviney** [comment]
@markst This isn't so much an issue with the podspec but more just how cocoapods works. By default it will only link pods to whatever it determines to be the primary target

**Comment by StevenDiviney** [comment]
@markst This isn't so much an issue with the podspec, its more how cocoapods works. It only links pods to whatever it determines to be the primary target. https://guides.cocoapods.org/syntax/podfile.html#group_target_configuration

Sorry about closing the issue, brain fart on my part.

**Comment by StevenDiviney** [comment]
Also thanks for the suggestion about NSAttributedString, I'll go and put that fix in now :)

**Comment by StevenDiviney** [comment]
https://github.com/zendesk/zendesk_mobile_ios_sdk/pull/609

**Comment by markst** [comment]
odd that zendesk doesn't appear as a target within my Pods project:
![image](https://cloud.githubusercontent.com/assets/274318/10807504/8505f55e-7e34-11e5-92f6-a01645721609.png)

is that a error on my part? or just the nature of the Zen static library pod?

**Comment by StevenDiviney** [comment]
Again this is just down to how Cocoapods works. If you look in the search paths of the Pods target you should see the ZendeskSDK. 

This is because we distribute the SDK as a pre-compiled framework so cocoapods just needs to link to it. All of the targets in your above screen shot are for frameworks that need to be compiled first, hence they each have their own build target.

**Comment by baz8080** [comment]
Closing this issue. Please feel free to open a new one if you have a new issue :)
