### ISSUE TITLE
Requests/Comments

### ISSUE THREAD

**Issue by Sky** [zendesk/zendesk_sdk_ios#129]
1. I created Request with ZDKAnonymousIdentity where email = "nil" and remember it's requestID.
2. Changed ZDKAnonymousIdentity to different one with email != "nil".
3. Now I can fetch Request created with email = "nil", but when trying fetch Comments for this Request getting error 403.

I need remember Requests created with not logged in user and than show them again when user logged in, how can I do this? Using same ZDKAnonymousIdentity.externalId for both also not helping.

**Comment by pierrezen** [comment]
For security concerns, if you change an email address or the external id of an existing identity, the SDK will be recreating a new identity so unfortunately, you will not be able to achieve what you are trying to do. 

Our customers with the need to know the user email will usually ask for it in the UI before the initialisation of the SDK so that the identity can be created with all relevant information set.

**Comment by Sky** [comment]
So you have a bug because I can fetch Requests created by different users.

**Comment by pierrezen** [comment]
As we will need more information regarding your account to investigate the issue you are raising, please  contact us at support.zendesk.com and we will follow up with you.

**Comment by Sky** [comment]
How it is related to my account info? :)
I can fetch Requests created by one ZDKAnonymousIdentity instance from another ZDKAnonymousIdentity instance if i know those requests IDs.
I don't want to write you at support.zendesk.com because I don't care, it's not making troubles for me but it's not fit to what you describe in your comment about security concerns, so it's a bug.
