### ISSUE TITLE
Disabled Help Center Category still visible.

### ISSUE THREAD

**Issue by capecrawler** [zendesk/zendesk_sdk_ios#169]
I tried to disable a category to hide it but it didn't reflect on the app. I was using `- (void) getCategoriesWithCallback:(ZDKHelpCenterCallback)callback;` of `ZDKHelpCenterProvider ` to load the categories. The following are the steps I did.

1. Disabled a category - didn't reflect in the app.
2. Added a new category - was able to see the new category in the app.
3. Removed the new category - still visible in the app.

But what's weird is it is working properly on other devices. I have this one device (iPhone 6) the keeps on retaining added categories. (I have installed same build of the app on these devices).

**Comment by oarrabi** [comment]
Hello @capecrawler ,

Thanks for reaching out.
I just tried to reproduce this issue, but was unable to.
Considering that this issue happens inconsistently only on one of your devices. And since we dont cache any requests in the SDK. 

Would it be possible for you to try to debug the network on this particular device? (using Charles web proxy or any other similar app)
Also, does it happen on any version of the simulator? (please try iPhone 6 and the same version of the iOS thats on your iPhone 6 device).

Thanks,
Omar...

**Comment by capecrawler** [comment]
I have tried it on the simulator and also can't reproduce the issue. Will try debugging the network. Thanks!

**Comment by tecknut** [comment]
Hey @capecrawler, did you find a solution to this issue?

**Comment by RonanMcH** [comment]
Hi @capecrawler , 
As we haven't heard from you for a while about this issue, I am going to close it for now. Feel free to reopen it if the issue persists for you.
Thanks,
Ronan.
