### ISSUE TITLE
Rate pop up lag

### ISSUE THREAD

**Issue by grabbou** [zendesk/zendesk_sdk_ios#19]
If opened manually by calling "alwaysOpen", there's a lag between clicking and showing the modal. I suppose it's because of HTTP request being made in the background to fetch app details? Anyway, it makes this feature slightly unusable as nobody is going to wait 2 seconds.

**Comment by BPlano** [comment]
@grabbou, 

Ah! This is actually an easy one :)

You should be able to change this in your app settings in your Zendesk SDK admin configuration. In this screenshot, the delay is 3 seconds, but you can set it to zero for near-instantaneous notifications.

![sdk_settings](https://cloud.githubusercontent.com/assets/5168423/6373102/5176e1f8-bcce-11e4-9aa0-888e5491b5b8.png)

If you have further questions, feel free to contact us at support@zendesk.com. Happy SDKing!

**Comment by jaanushansen** [comment]
There still is a problem - You can't change the delay to 0, it just is not allowed.

**Comment by jaanushansen** [comment]
Unfortunately there still is a problem - the form do not allow to change Delay value to 0.

**Comment by dangochi** [comment]
Sorry for commenting on an old/closed issue, and I know this isn't an SDK bug since the admin console doesn't allow you to set the delay to 0, but it seems like others have requested this, so I was curious if we'd ever be allowed to show the RMA dialog without a delay? 

I saw @tecknut mentioned on #70 that he'd log an issue with the server guys to fix it, but I haven't really seen much regarding this since then.
