### ISSUE TITLE
Question, how to pull back "my tickets"

### ISSUE THREAD

**Issue by MaximusMcCann** [zendesk/zendesk_sdk_ios#193]
ZDKRequestListViewController has been added to the screen and I've set the identity.
A ticket was created with the "+" icon in the upper right and after sending is present in the tableView.
After logging out and logging back in (and re-setting the ZD identity) I see no tickets.

How do I tell ZDKRequestListViewController to pull down the remote tickets?

**Comment by MaximusMcCann** [comment]
Have also tried `ZDKRequests.presentRequestListWithViewController(Router.currentVC)`, but with the same result.

**Comment by mathewcropper** [comment]
Hi Maximus. If you have chosen to use anonymous authentication this is the expected behaviour. We treat anonymously authenticated users as untrusted, and so changing users or reinstalling the device gives them a new profile each time. That's why you can't see old tickets from before the reset, or tickets created from other channels.

If you'd like to be able to have tickets follow the end-user around, you'll need to use JWT authentication instead. This is a trusted method of authentication, and will allow you to achieve what you need.

You may find the following resources useful:

* [Authenticating users](https://developer.zendesk.com/embeddables/docs/ios/authentication) developer docs for iOS.
* [Authenticating users](https://developer.zendesk.com/embeddables/docs/android/authentication) developer docs for Android.
* The [integration checklist](https://support.zendesk.com/hc/en-us/articles/217914138-Zendesk-SDK-integration-checklist), which has a section about authentication.
