### ISSUE TITLE
拉取不到之前用户的tickets

### ISSUE THREAD

**Issue by Zhangguiguang** [zendesk/zendesk_sdk_ios#214]
ZDKAnonymousIdentity *identity = name:@"a", email:A's email
[ZDKConfig instance].userIdentity = identity;
A 创建了一个ticket1
之后切换用户B, identity = name:@"b", email:B's email
B 查看tickets is empty.
之后再换回A, identity = name:@"a", email:A's email
这时 A 查看tickets is empty，ticket1 却找不回来了。

**Comment by mathewcropper** [comment]
Hi. Unfortunately, I'm unable to provide support in Chinese. I'll try to answer your question as I understand it, but if you need help in your own language it may be better to visit support.zendesk.com and raise a ticket.

It sounds like you have the following problem:

- You are using anonymous authentication in your app
- You create an identity with one set of details (A), and create a ticket
- You then change the details of the identity to something else (B), and see the request list is empty
- You then change the details back to (A), and the request list is still empty

This is expected behaviour. An anonymous identity is an untrusted one, and when the elements that construct that identity are changed, we create a new end-user. When that happens, access to the old end-user on that device is lost forever.

To avoid this, you should use JWT authentication instead. This is a trusted method of authentication, and it means that your end-user's tickets will always be available to them. You can find out more about JWT auth on iOS here: https://developer.zendesk.com/embeddables/docs/ios/authentication#using-jwt-authentication

**Comment by Zhangguiguang** [comment]
You're so clever, and your answer solved my question. Thank you.
