### ISSUE TITLE
Providing both external id & email for anonymous identification.

### ISSUE THREAD

**Issue by nikita-leonov** [zendesk/zendesk_sdk_ios#215]
Currently external id & email used for identification. Meanwhile email is also needed for communication. Most of users in a system have external id, and only some of them may have email address. When both email & external id provided both of them should be used. Currently it is not the case. If both provided only external id is used and email discarded, as result there is no way to communicate with users.

**Comment by tecknut** [comment]
@nikita-leonov We have seen issues like this in the past. The issue is usually due to issues with the external id of the users. 

It might be best if you opened a ticket with us on [support.zendesk.com](https://support.zendesk.com) because we may need some account details to look into logs. 

Thanks

**Comment by tecknut** [comment]
You might give this issue as a reference on the ticket as it will probably need to be escalated.

**Comment by tecknut** [comment]
Hey @nikita-leonov, just following up on this. I haven't seen anything related to this issue in our support channel. Did you managed to resolve the issue?

**Comment by nikita-leonov** [comment]
We workarounded it by introducing custom field for user id for our previous release. I created a ticket now —  https://support.zendesk.com/hc/requests/1787531.
