### ISSUE TITLE
Can't embed zendesk viewcontroller in container

### ISSUE THREAD

**Issue by jerydarkside** [zendesk/zendesk_sdk_ios#22]
Hi !
It seems that if the viewcontroller that call the zendesk system is embeded in a container view controller, the zendesk system can't push the detail view controller of a ticket.

**Comment by jimspeth** [comment]
It appears that tapping a ticket attempts to present the detail view using `+[ZDKUIViewController presentViewController:requiresNavController:]` which requires that the window's rootViewController have a navigationController.  If the rootViewController returns nil for its navigationController, the following is logged:

`WARNING! Requires navigation has been set to YES, but no navigation controller is present.`

Instead of using this class method, why doesn't the ZDKRequestListViewController use its own navigation controller to present the view?

We worked around this in our app by overriding navigationController in our container view to return the navigation controller of one of the contained view controllers.

**Comment by BPlano** [comment]
Hey @jerydarkside and @jimspeth -

This should be fixed as of SDK version 1.1.1.1 - please update to the latest version in your implementation. Thanks!
