### ISSUE TITLE
zendesk navigation bar  ui error 

### ISSUE THREAD

**Issue by sunilhts** [zendesk/zendesk_sdk_ios#242]
Zendesk SDK version: 1.6.2.1
Xcode version:7.3.1
iOS or Simulator: iPhone6s
iOS Version: iOS 9.3
Swift version:2.2
Using Cocoapods, cocoapods version 0.39.0

Please open the link to know the issue..
http://stackoverflow.com/questions/39994645/zendesk-default-help-center-ui-error

**Comment by RonanMcH** [comment]
Hi @sunilhts ,
This UI state usually happens when the `ZendeskSDKStrings.bundle` is not linked correctly to the target from where you are launching the Zendesk SDK. Cocoapods usually does this linking. Are you sure you have configured your `podfile` to add the SDK and its bundles to the right target? Can you show us your podfile snippet?
Thanks,
Ronan

**Comment by RonanMcH** [comment]
Hi @sunilhts ,
We haven't heard from you in a while. I am going to tentatively close this issue.  Please feel free to reopen it if this is still an ongoing issue for you.
Thanks,
Ronan.
