### ISSUE TITLE
Reentering a chat from a modal view messes up the layout.

### ISSUE THREAD

**Issue by nickfalk** [zendesk/zendesk_sdk_ios#246]
- SDK version: 1.7.1.1
- Xcode version: Version 8.0 (8A218a)
- iOS or Simulator: Both
- iOS Version: 9.3, 10.0 (at least)
- Swift version: 2.3

When reentering a chat inside a modally presented viewController the whole viewController is forced down 44 (or so) points. This only occurs if the chat is initiated _and_ reentered from the _same_ modally presented controller.

![zendeskbug](https://cloud.githubusercontent.com/assets/1871987/19431570/42ea39d2-9459-11e6-8d12-958494fa57cb.gif)

It seems somewhat similar to part of this issue: https://github.com/zendesk/zendesk_sdk_ios/issues/18 posted in January 2015

I am, as of yet, unable to write a _simple_ viewController to reproduce the problem, it seems the inherit complexity of our controller might be part of the reason the problem occurs.

**Comment by ndobri** [comment]
@nickfalk it looks like the offset is the exact height of the nav bar. This might be due to [automaticallyAdjustsScrollViewInsets](https://developer.apple.com/reference/uikit/uiviewcontroller/1621372-automaticallyadjustsscrollviewin) property on a ViewController. 

Can you log the `automaticallyAdjustsScrollViewInsets` value before and after the modal is shown? 

Is what you have there a container ViewController with child elements for the photo preview and the preferences list?

Also, could you slow down the animations on the simulator and redo the screen grab as you've done above?

**Comment by nickfalk** [comment]
Thanks,
I've logged the `automaticallyAdjustedScrollViewInsets` and they remain `true` throughout.

The view you are watchings is actually a tableView, the photo-preview being the tableView's headerView.

Slow-motion version:
![zendeskbugslowmo](https://cloud.githubusercontent.com/assets/1871987/19469470/c0174568-951b-11e6-85b7-17dc458d4620.gif)

**Comment by tecknut** [comment]
Hi @nickfalk, can you try something for us please?

Set `automaticallyAdjustedScrollViewInsets` to false on that view controller. This will probably move the header up underneath the nav bar initially. 

We want to see if the view is still pushed down when this property is set to false, so that we can eliminate it from the possible causes. 

Could you additionally provide a code snippet for the initial launching of Chat in the view controller?

Thanks

**Comment by nickfalk** [comment]
Good call, 
as expected the header is moved under the navigation-bar initially. It does however _not_ move again when I normally will see the above described bug(!)

**Comment by RonanMcH** [comment]
Hi @nickfalk ,
In order for us to continue debugging this isuue, could you supply us with the code snippet that you are using to launch the chat initially?
Thanks,
Ronan.

**Comment by tecknut** [comment]
@nickfalk This has been inactive for a while. We'll close this in a week if there's no update.
