### ISSUE TITLE
Crash on custom fields

### ISSUE THREAD

**Issue by Jorrit2002** [zendesk/zendesk_sdk_ios#253]
- SDK version: 1.7.x.x
- Xcode version: 8 
- iOS or Simulator: IOS
- iOS Version: 10
- Swift version: 3

After upgrading my project to Swift 3 my app crashes when I'm trying to create a ticket. 
Using: 
  
```
 let helpCenterContentModel = ZDKHelpCenterOverviewContentModel.defaultContent()
 ZDKHelpCenter.pushOverview(self.navigationController, with:helpCenterContentModel)
```

> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_SwiftValue fieldId]: unrecognized selector 

It seems my custom fields are a part of the problem. When I'm removing those everything works fine. Does someone have a solution?

`ZDKConfig.instance().customTicketFields = [ my custom fields ]
`

**Comment by oarrabi** [comment]
Hello @Jorrit2002 

Can you please post the snippet of code that you are using to set the custom ticket fields?

Thanks

**Comment by Jorrit2002** [comment]
```
let customFieldPlatform = ZDKCustomField(fieldId: 28803605, andValue: "ios")
let customFieldAppVersion = ZDKCustomField(fieldId: 28803625, andValue: appVersion)
let customFieldOsVersion = ZDKCustomField(fieldId: 28654469, andValue: UIDevice().systemVersion)
let customFieldDeviceModel = ZDKCustomField(fieldId: 28803665, andValue: UIDevice.current.modelName) //ZDKDeviceInfo.deviceType())
let customFieldDeviceMemory = ZDKCustomField(fieldId: 28803685, andValue: String(ZDKDeviceInfo.totalDeviceMemory()))
let customFieldFreeSpace = ZDKCustomField(fieldId: 28654489, andValue: String(ZDKDeviceInfo.freeDiskspace()))

```

**Comment by StevenDiviney** [comment]
@Jorrit2002 This is happening because ZDKCustomField is an Objective C type, and therefore optional. This optional is getting passing into out Objective C SDK which does not know how to handle it.

This can be fixed by force unwrapping all the ZDKCustomField objects.
```
ZDKConfig.instance().customTicketFields = [ customFieldPlatform!, etc... ]
```

This is happening because of a change to the swift compiler. In Swift 2 when an optional type was passed through to Objective C it was unwrapped. In Swift 3 all unbridged types are automatically wrapped in an Objective C class "SwiftValue". This is why you were seeing unrecognized selector errors, our SDK was trying to pull custom field values from SwiftValue.

I will update our known issues and open an issue internally for us to fix this.

Thank you for bringing it to out attention.
