### ISSUE TITLE
CustomField value not sending

### ISSUE THREAD

**Issue by MaximusMcCann** [zendesk/zendesk_sdk_ios#262]
- SDK version: 1.7.6.1
- Xcode version: 8.1 (8B62)
- iOS or Simulator: Simulator iPhone 5 (10.1)
- iOS Version: 10.1
- Swift version: 3

Steps to Reproduce:

```
// Setup ZDK
ZDKConfig.instance().customTicketFields = [ZDKCustomField(fieldId: 49211xxx, andValue: "TESTT")]// Must come before ZDKCreateRequestViewController    
let ticketVC: ZDKCreateRequestViewController = ZDKCreateRequestViewController()
//Present VC
//Submit
//Check ZD, no "TESTT" in custom field
```

After sending the ticket I do not see the Custom field populated with the value "TESTT".  Help would be appreciated. 

The only docs I've found are: https://developer.zendesk.com/embeddables/docs/ios/add_data_to_request

> To add data to a custom ticket field, you must add it to ZDKConfig before you show the create request screen to your end-user.

Cheers!

**Comment by mathewcropper** [comment]
Hey! Is the custom field set to both 'visible' and 'editable' in the Zendesk Support admin?

If it is, and you still have the problem, could you enable logging and share the output? https://developer.zendesk.com/embeddables/docs/ios/debug

**Comment by MaximusMcCann** [comment]
I don't want the field visible to the end user :/.  I do not see an 'editable' option either

**Comment by MaximusMcCann** [comment]
Should only be visible to our staff.  It's a UID for errors

**Comment by mathewcropper** [comment]
That'll be why this isn't working. To populate a custom field using the Support SDK the field must be visible and editable in the settings. 

Once you click the visible tick box in the settings, the editable tick box will appear. 

I'm afraid this isn't something that can be circumvented. If the field really cannot be updated to be visible and editable, then I would suggest that using the API directly, instead of the SDK, may be the way to go. 

I'll mark this as closed for now, as we have found the solution, but feel free to continue the discussion here if you have questions.
