### ISSUE TITLE
"Unable to Connect" on ZDKHelpCenterOverviewController

### ISSUE THREAD

**Issue by OlesenkoViktor** [zendesk/zendesk_sdk_ios#277]
- SDK version: Latest 1.9.0.1
- Xcode version: 8.2.1
- iOS or Simulator: Simulator
- iOS Version: 9.3
- Swift version: 3.1

Steps to Reproduce:

AppDelegate
`Fabric.with([Crashlytics.self, STPAPIClient.self, Zendesk.self])
        ZDKConfig.instance().userIdentity = ZDKAnonymousIdentity()
        ZDKLogger.enable(true)`

Controller
`newNC = UIStoryboard(name: "Support", bundle: nil).instantiateViewController(withIdentifier: kSupportStoryboardID) as! UINavigationController
newNC.navigationBar.tintColor = UIColor.white
let vc = ZDKHelpCenterOverviewController(helpCenterOverviewModel: ZDKHelpCenterOverviewContentModel.defaultContent())
newNC.viewControllers = [vc]`

Logs
[DEBUG]: Response code [0x7fb686b324b0]: 200
[DEBUG]: Request success: [0x7fb686b324b0]: https://possio.zendesk.com//hc/api/mobile/en-gb/articles.json?sort_by=created_at&sort_order=desc&include=categories,sections&limit=5&per_page=1000
[INFO]: Localization key and value : "ios.ZDKHelpCenter.support.contactError" = "Unable to connect";
[INFO]: Localization key and value : "ios.ZDKHelpCenter.toastRetryButton" = "Retry";`

Result:
Unable to connect error on screen
[Screenshot of result](http://imgur.com/a/TM6Pn)

**Comment by RonanMcH** [comment]
Hi @OlesenkoViktor ,
I haven't been able to reproduce this issue. It looks like the network request is a success but the error toast is still being triggered. Does this happen intermittently or consistently? Can you recreate it in a sample application? 
Thanks,
Ronan.

**Comment by OlesenkoViktor** [comment]
Hi @RonanMcH 
Sure - attached. Issue is still reproducing
[ZendeskIssue277.zip](https://github.com/zendesk/zendesk_sdk_ios/files/817835/ZendeskIssue277.zip)

**Comment by StevenDiviney** [comment]
@olenavelykanova Thanks for sending on your project. I have removed your post as it contains details specific to your account.

You are seeing a "No Connection" toast because your Help Center has no content. The toast should not show in this case, it is a bug. I have created an issue for us to track this internally.

Once you add content to your Help Center the SDK should work as expected.

**Comment by couldhll** [comment]
+1

**Comment by divo** [comment]
@couldhll Are you seeing this issue? Could you open a new issue so we can address it?

**Comment by couldhll** [comment]
It work fine for me, thanks.

**Comment by mad102190** [comment]
This happens to me as well. Most devices/users can access it fine, however some can **never** connect and others connect intermittently. We've verified that this isn't due to a network issue. We have plenty of content in our Help Center and for the most part it works ok, but we need to figure out why this is happening to some users, preventing them from EVER seeing the help center in our app.

**Comment by mad102190** [comment]
Bump. 

I've figured out that some users who try to access the help center in our app get a 403 response. It looks like the app is actually trying to call the `https://varomoney.zendesk.com/hc/api/mobile/en-us/articles.json` endpoint *first* with a null auth token, then they get a 401, then it tries to call `https://varomoney.zendesk.com/access/sdk/anonymous` and gets a 403.

With users who *can* access the help center, this is done in the opposite order, the app calls the `/access/sdk/anonymous` endpoint first, gets a 200, then requests the articles successfully. 

Any idea what's happening.
