### ISSUE TITLE
Tickets not loading if app uninstalled and logged in with the same user using ZDKAnonymousIdentity

### ISSUE THREAD

**Issue by marcmatta** [zendesk/zendesk_sdk_ios#305]
- SDK version: 1.9.2.2
- Xcode version: 8.2
- iOS or Simulator: Both
- Using ObjC

Steps to Reproduce:

1. Install App and Login to that app.
2. Login and set ZDKConfig.instance userIdentity using a ZDKAnonymousIdentity with external Id xxx, email and name
3. Create ticket
4. Uninstall app
5. Install app again and Login with the same user used in step 1
6. Login and set ZDKConfig.instance userIdentity using a ZDKAnonymousIdentity with external Id xxx, email and name

**Resulting behavior:**

Tickets for that user are not showing for the user in question.

**Expected behavior:**

Tickets for the same user should appear again when signed it using an anonymous identity with the same external Id.

**Question:**

Please correct me if I'm wrong with what the expected behavior should be. If I've missed initializing the SDK somehow, I'd appreciate some pointers to help figure out the issue.

**Comment by RonanMcH** [comment]
Hi @marcmatta ,
this is the expected behaviour.  This will be a new user if you uninstall the application and you use anonymous identification. This is because an anonymous identity is an untrusted one.  If you want users to be trusted and be able to view their tickets across devices(installs of the application), then consider switching over to JWT identification. Let us know if you have anymore questions.
Thanks,
Ronan.

**Comment by marcmatta** [comment]
Thanks @RonanMcH!
