### ISSUE TITLE
Invalid response object from ZDKRequestProvider createRequest method.

### ISSUE THREAD

**Issue by matkuznik** [zendesk/zendesk_sdk_ios#410]
- SDK version:
2.0.3
- Xcode version:
9.4.1
- iOS or Simulator:
iPhone X
- iOS Version:
11.3
- Swift version:
Apple Swift version 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)

Steps to Reproduce:
1. Create `ZDKRequestProvider` object
2. Create `ZDKCreateRequest` with required fields
3. Use `[ZDKRequestProvider  createRequest:(ZDKCreateRequest*)request withCallback:(ZDKCreateRequestCallback)callback]`

Issue:
In the `ZDKCreateRequestCallback` the `result` object is type of `ZDKDispatcherResponse`. 
I believe it should be `ZDKRequest`

**Comment by tecknut** [comment]
Hi @matkuznik, 

Thanks for you reaching out to us. 

The [`ZDKCreateRequestCallback`](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskSDK/4.0/ZendeskProviderSDK.framework/Headers/ZDKRequestProvider.h#L65) result type is actually an `id`. 

The [`ZDKDispatcherResponse`](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskSDK/4.0/ZendeskProviderSDK.framework/Headers/ZDKDispatcherResponse.h) has been the response type for create request since the provider was introduced. 

Is there something specific you were trying to achieve? Maybe we can help figure something out?

Thanks,
Alan

**Comment by matkuznik** [comment]
hi,
thanks for the quick response :).

So, this is the intended approach.
I'm used to that create request returns an object that was created and I assumed that you have a missing mapping.

What I want to achieve is to present some success state for the user and if I would have a created request object, then I could use data which for sure are saved in your system. Also, an id of a created object could be helpful for caching purpose or avoiding additional requests.

For now, I'm just parsing provided JSON but this is far away from the ideal solution.

**Comment by tecknut** [comment]
There is a request object in that response, though there is also a comment object. 

Are you building your own UI?

**Comment by matkuznik** [comment]
Yes, we are.

In `ZDKDispatcherResponse` has two properties: an `NSHTTPURLResponse` and an `NSData` which is a JSON.

Or I miss something?

**Comment by tecknut** [comment]
You can deserialise the data to a Dictionary. This will contain two objects keyed by `request` and `last_comment`. 

[`ZDKRequest`](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskSDK/4.0/ZendeskProviderSDK.framework/Headers/ZDKRequest.h#L112) can be initialised from a dictionary. Which should will give you want you want. 

It's worth mentioning that [we also have an API](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskSDK/4.0/ZendeskProviderSDK.framework/Headers/ZendeskProviderSDK-Swift.h#L331) which gives you a cached updates on requests opened by the current user. 

It might be something you can use.

**Comment by matkuznik** [comment]
Awesome. 

Thank you for your help :)
