### ISSUE TITLE
No way to know when a user taps Ticket Creation button from HelpCenterUi

### ISSUE THREAD

**Issue by juanpdelat** [zendesk/zendesk_sdk_ios#414]
- SDK version: 2.0.3
- Xcode version: 9.4.1 
- iOS or Simulator: Both
- iOS Version: 10
- Swift version: 4.1

There are no methods in the ZDKHelpCenterConversationsUIDelegate to detect when an event has occurred, in fact, ZDKHelpCenterConversationsUIDelegate is more like a Data Source, because it doesn't really allow the delegating object to handle events, just setting up data to be used for presenting the UI.

Steps to Reproduce:
1. Present a HelpCenterUi
2. Tap Ticket Creation button on top right
3. At this point, I'd like to know that a new ticket will be created or a list of previous tickets is opened.

**Comment by HamstringAssassin** [comment]
Hi @juanpdelat, 

Thanks for getting in touch. You're correct, I'm afraid that functionality isn't available. Another option for you might be to roll your own UI. We have provider methods available. More information can be found here: 
https://developer.zendesk.com/embeddables/docs/ios_support_sdk/api_provider_using

We also keep an eye here for feature requests so that could be a perfect place to put this. https://develop.zendesk.com/hc/en-us/community/topics/360000018828-Mobile-SDKs

Thanks a mil, 
Al
