### ISSUE TITLE
Can't swipe to go back from Request to Request List

### ISSUE THREAD

**Issue by CraigSiemens** [zendesk/zendesk_sdk_ios#420]
- SDK version: 2.1.0
- Xcode version: 9.4
- iOS or Simulator: Both
- iOS Version: 11.4
- Swift version: 4.1.2

Steps to Reproduce:
1. Present the request list modally
```
let requestListVC = RequestUi.buildRequestList()
let requestNavigationController = UINavigationController(rootViewController: requestListVC)
viewController.present(requestNavigationController, animated: animated, completion: nil)
```
2. Navigate to a request
3. Try to swipe from the left edge of the screen to go back to the request list

**Comment by KillianSmith0** [comment]
Hi @CraigSiemens ,

This is the expected behaviour of our SDK. The reason for this is caused by the discard message alert message. We can't catch the event on swipe, so the type message will be lost. If you like you could [submit a feature request](https://develop.zendesk.com/hc/en-us/community/topics/360000000788-Feature-Requests), but there's no current plans to implement this gesture.

Regards,
Killian
