### ISSUE TITLE
Xcode 9 crash on ZendeskSDK 2.1.1

### ISSUE THREAD

**Issue by yahalawa** [zendesk/zendesk_sdk_ios#438]
Hi so I just started using ZendeskSDK v2.1.1 and it has the fix for Xcode 10 which is great, but it does not work on Xcode 9 (regardless of which build system I choose). I get the following error on first launch of app:
dyld: Symbol not found: _$SBOWV
Referenced from: /private/var/containers/Bundle/Application/...Frameworks/ZendeskCoreSDK.framework/ZendeskCoreSDK
Expected in: /private/var/containers/Bundle/Application/.../Frameworks/libswiftCore.dylib
in /private/var/containers/Bundle/Application/.../Frameworks/ZendeskCoreSDK.framework/ZendeskCoreSDK

**Comment by KillianSmith0** [comment]
@yahalawa Xcode 10 uses Swift 4.2, and Xcode 9.4 uses Swift 4.1.2. Since Swift isn't abi compatible, you will have to choose the set of frameworks that were built with the aligning Xcode command line tools.. 
If you're integrating via cocoapods, you will have to drag the Swift 4.1.2 binaries, into your Pods/ZendeskSDK/ folder.. Same applies for manual integration, just pull in the required set of binaries from our repo

**Comment by yahalawa** [comment]
@KillianSmith0 can you elaborate more on how to drag the Swift 4.1.2 binaries? Where do I find them? Also I thought Xcode 10 comes with Swift 4.2 but it is not enabled by default (meaning we would have to perform a migration) so In my case we still have not done that so both Xcode 9 and 10 should be on Swift 4.0 right now

**Comment by iosnativedeveloper** [comment]
@yahalawa are you able to resolve this issue. As I am also getting the same error while running a project in a device.

**Comment by KillianSmith0** [comment]
@yahalawa @iosnativedeveloper 
Open `ZendeskSDK/4.1` folder (these are the 4.1.2) artefacts.. Copy the contents.. Go to your frameworks folder and paste them in! Then go to your project file, and under `General` make sure the frameworks are linked under `linked frameworks and libraries`
