### ISSUE TITLE
iPhone X layout issues - Message box covering whole screen

### ISSUE THREAD

**Issue by Sroka** [zendesk/zendesk_sdk_ios#506]
- SDK version: 1.4.0
- Xcode version: 10.2
- iOS or Simulator: iPhone X
- iOS Version: 11.4
- Swift version: 4.2

Steps to Reproduce:

1. Open chat with` ZDCChat.start(in: nil, withConfig: nil)`
2. Click on a message box
3. Click Done
4. Click on a message box again

ER: Message box stays at the bottom of the screen
AR:
<img width="416" alt="image" src="https://user-images.githubusercontent.com/2983710/56647090-263f2e80-6681-11e9-9b60-e1db29a7fa4e.png">

**Comment by tecknut** [comment]
Hi @Sroka, 

This repository is for the Support SDK. This issue is with the Chat SDK. The [contributing](https://github.com/zendesk/zendesk_sdk_chat_ios/blob/master/CONTRIBUTING.md#issues) guide for Chat SDK details opening a ticket with us. 

Can you open a ticket with us there please? 

Thank you,
Alan
