### ISSUE TITLE
iPhone X layout issues - Navigation bar not respecting notch space

### ISSUE THREAD

**Issue by Sroka** [zendesk/zendesk_sdk_ios#507]
- SDK version: 1.4.0
- Xcode version: 10.2
- iOS or Simulator: iPhone X
- iOS Version: 11.4
- Swift version: 4.2

Steps to Reproduce:

1. Open chat with` ZDCChat.start(in: nil, withConfig: nil)`
2. Click on a message box

ER: Navigation bar is displayed under the iPhone X notch
AR:
<img width="430" alt="image" src="https://user-images.githubusercontent.com/2983710/56647295-846c1180-6681-11e9-896d-7cff06529a75.png">

**Comment by tecknut** [comment]
Hi @Sroka, 

This repository is for the Support SDK. This issue is with the Chat SDK. The [contributing](https://github.com/zendesk/zendesk_sdk_chat_ios/blob/master/CONTRIBUTING.md#issues) guide for Chat SDK details opening a ticket with us. 

Can you open a ticket with us there please? 

Thank you,
Alan
